defaults:
  - model: linear_ae
  - optimizer: adam
  - loss: mse
  - _self_

mlflow:
  tracking_uri: ${oc.env:MLFLOW_TRACKING_URI, file:${oc.env:PROJECT_ROOT}/artifacts}

  artifacts:
    dir: ${oc.env:PROJECT_ROOT}/artifacts

data:
  train:
    data_dir: ./data/mnist
    train: true
    batch_size: 64
    shuffle: true
    num_workers: 4

  val:
    data_dir: ./data/mnist
    train: false
    batch_size: 64
    shuffle: false
    num_workers: 4

training:
  epochs: 5000
  random_seed: 47
  device: mps

callbacks:

  early_stopping:
    patience: 10
    monitor: val_loss
    mode: min
    min_delta: 1e-6
    start_from_epoch: 5

  model_checkpoint:
    monitor: val_loss
    mode: min
    min_delta: 1e-3
    start_from_epoch: 0
