model:
  name: autoencoder

  params:
    latent_dim: 16
    conv_filters: 128
    input_dim: [1, 600]


  experiment:
    # Uses model.name
    name: "Autoencoder_${model.params.latent_dim}"

    # Uses model.name, latent_dim, and timestamp
    run_name: "${model.name}_L${model.params.latent_dim}_conv${model.params.conv_filters}_${now:%H%M%S}"

data:

  train: 
    dataset_path: /Users/alexdelapuente/Desktop/h5vectorized/tr
    fraction: 0.7
    features_info: false
    neighbours_info: false
    ref_info: true
    batch_size: 512
    shuffle: true
    num_workers: 6
  
  val: 
    dataset_path: /Users/alexdelapuente/Desktop/h5vectorized/vl
    fraction: 0.5
    features_info: false
    neighbours_info: false
    ref_info: true
    batch_size: 512
    shuffle: true
    num_workers: 6

callbacks:

  early_stopping:
    patience: 10 #200 # 30-50 para el latent
    monitor: val_loss
    mode: min
    min_delta: 1e-6
    start_from_epoch: 30 #30 # 100
    
  model_checkpoint:
    monitor: val_loss
    mode: min
    min_delta: 1e-3
    start_from_epoch: 0 #30 # 100

  ae_viz_callback:
    val_data_dir: /Users/alexdelapuente/Desktop/h5vectorized/vl
    cubes: [2, 4, 9]
    scalers:
      series_scaler.joblib: series_scaler
    n_layers_per_cube: 3
    n_vectors_per_layer: 3
    plot_every_n_epochs: 10


# training:
#   epochs: 500

# callbacks:
#   early_stopping:
#     patience: 12 
#     metric: val_mae
#     mode: min
#     min_delta: 1e-6
#     start_from_epoch: 50 

#   model_evaluation:
#     val_dir: /Users/alexdelapuente/Desktop/itp_fabad/data/data_raw # raw data path
#     global_uncertainty: /Users/alexdelapuente/Desktop/itp_fabad/stats_data/global_uncertainty.npz
#     stats: /Users/alexdelapuente/Desktop/itp_fabad/data/vectorized_cubes/all_stats.npz
#     plot_interval: 200
#     num_layers: 10
#     vector_per_layer: 2

# # modificar en caso de querer continuar el entrenamiento de algún modelo
# # se debe especificar el run_id del modelo en mlflow
# resume_training: null

# train_with_mean_ref_data: True
