model:
  name: conv_vae

  params:
    in_channels: 1
    channels_bottleneck: 4

  experiment:
    name: "ConvVAE_B${model.params.channels_bottleneck}"
    run_name: "conv_vae_B${model.params.channels_bottleneck}_${now:%H%M%S}"

loss:
  name: vae_loss
  kl_weight: 0.8
  reconstruction_weight: 1.0

data:
  train:
    data_dir: ./data/mnist
    train: true
    batch_size: 64
    shuffle: true
    num_workers: 4
  val:
    data_dir: ./data/mnist
    train: false
    batch_size: 64
    shuffle: false
    num_workers: 4

optimizer:
  name: adam
  lr: 5e-4

callbacks:
  early_stopping:
    patience: 10
    monitor: val_loss
    mode: min
    min_delta: 1e-6
    start_from_epoch: 5

  model_checkpoint:
    monitor: val_loss
    mode: min
    min_delta: 1e-3
    start_from_epoch: 0
