model:
  name: linear_ae

  params:
    latent_dim: 2

  experiment:
    name: "LinearAE_L${model.params.latent_dim}"
    run_name: "linear_ae_L${model.params.latent_dim}_${now:%H%M%S}"

data:
  train:
    data_dir: ./data/mnist
    train: true
    batch_size: 64
    shuffle: true
    num_workers: 4
  val:
    data_dir: ./data/mnist
    train: false
    batch_size: 64
    shuffle: false
    num_workers: 4

optimizer:
  name: adam
  lr: 5e-4

callbacks:
  early_stopping:
    patience: 10
    monitor: val_loss
    mode: min
    min_delta: 1e-6
    start_from_epoch: 5

  model_checkpoint:
    monitor: val_loss
    mode: min
    min_delta: 1e-3
    start_from_epoch: 0

  reconstruction_viz:
    plot_every_n_epochs: 10
    n_samples: 8

  latent_space_viz:
    plot_every_n_epochs: 10
    max_points: 2048

  latent_interpolation_viz:
    plot_every_n_epochs: 10
    grid_size: 12

  random_generation_viz:
    plot_every_n_epochs: 10
    n_samples: 16
